### PR TITLE
Release ReaKontrol v1.00

### PR DESCRIPTION
**Pull request by brummbrum**
- added CUSTOM ACTIONS functionality
- user editable configuration file

### CODE REVIEW

**Comment by brummbrum** [comment]
Hi Christian,
I accidentally provided a wrong link for the 2nd file under @provides

Wrong: ReaKontrolConfig/reakontrol.ini https://stash.reaper.fm/manage_file/39830/reakontrol.ini
Correct:  ReaKontrolConfig/reakontrol.ini https://stash.reaper.fm/v/39830/reakontrol.ini

**Comment by cfillion** [comment]
Fixed the link. Noticing this was put in the API category, perhaps it would be best suited to move it into a new Control Surfaces category?

(Changing category means the current package will be marked obsolete and a new one will become available.)

**Comment by brummbrum** [comment]
Agreed. "Control Surfaces" would indeed be a better fit. But API is ok too... I doubt that people search via the categories. Leave it up to you - whatever you think works best for ReaPack.

I anticipate that another Reaper forum member (https://github.com/terminar) will soon publish the Mac port of ReaKontrol also via ReaPack. Currently, the Mac version it is only hosted on stash. At least this is what I suggested to him.

Maybe, by introducing a new Control Surfaces category, we could motivate more devs to publish via ReaPack (which I truly love btw- masterful work!). Control Surfaces seem to enjoy increasing popularity lately.... Thinking Geoff Waddington's CSI etc.

**Comment by brummbrum** [comment]
Just noticed yet another mistake with the link - aargh! Was too tired. Will fix this via the upload tool. Sorry!

https://stash.reaper.fm/v/39830/reakontrol.ini
https://stash.reaper.fm/39830/reakontrol.ini

**Pull request merged**
